name: 'Setup Python environment'
description: 'Install uv, Python, and project dependencies. Requires actions/checkout before this action.'


runs:
  using: 'composite'
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Install Python 3.14
      shell: bash
      run: uv python install 3.14

    - name: Install dependencies
      shell: bash
      run: uv sync --frozen

